# -*- coding: utf-8 -*-
"""random num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kJ5D3PbEjyAOGZ9SI736LDYIVpGJMDbi
"""

import random

int_arrival_time = 0
arrival_time = 0

print("Customer No.\t\t Inter Arrival Time\t\t\t Arrival Time")
for i in range(1, 51):
    if (i == 1):
        print("%i \t\t\t\t\t - \t\t\t\t\t\t\t %i" % (i, arrival_time))

    else:
        print("%i \t\t\t\t\t %i \t\t\t\t\t\t\t %i" % (i, int_arrival_time, arrival_time))

    int_arrival_time = random.randrange(1, 30)
    arrival_time = int_arrival_time + arrival_time

